### PR TITLE
feat: implement day divider config

### LINKED ISSUE #202: [mobile] Add day divider /spacer in list view

### PR DESCRIPTION
**Pull request by Alchez**
Closes #202.

---

image

### CODE REVIEW

**Comment by Alchez** [comment]
@agritheory I've currently added the day-dividers to just the "Manufacture" page. Let me know if other list views also need to be implemented, and what date to use for them.

**Comment by agritheory** [comment]
@alchez, let's also add them to Demand, Receive and Ship

**Comment by Alchez** [comment]
@agritheory I've added the day dividers to Demand (via `allocated_date`), Receive (via `schedule_date`) and Ship (via `delivery_date`). Let me know if the date references need to change.

**Comment by agritheory** [comment]
@Alchez Dates look correct. Can we get the background style color to extend the full width of the page? This probably means removing margin that's outside the listview

**Comment by Alchez** [comment]
@agritheory The margin issue is resolved by https://github.com/agritheory/stonecrop/pull/203.

**Comment by agritheory** [comment]
@Alchez Is the margin resolved with the updated dependencies?

**Comment by Alchez** [comment]
@agritheory Yeah, the lockfile will fetch the version with the margin fixes

**Pull request merged**
