### PR TITLE
fix: create handling units after submit

### LINKED ISSUE #144: Generate Handling Unit should be happening in `on_submit` hook instead of `before_submit` hook
But this causes the tests to fail in way that where it isn't obvious why - it appears that handling units aren't being generated

### PR DESCRIPTION
**Pull request by Alchez**
Closes #144 

---

I've changed the logic for setting the Handling Units directly into the database after creation.

image

### CODE REVIEW

**Comment by Alchez** [comment]
@agritheory So based on the failing tests, it seems like the Handling Units were set to be created on `before_submit` because they need to pass to the SLEs, which are created after submit.

If the HUs are created after submit as well, they won't be available in the SLEs anymore. I'm not sure what a good fix here is.

What do you think?

**Comment by agritheory** [comment]
I think we're back to `before_submit`. We just want to make that `before_submit` logic happens after the db rollback setpoint if there's an error in `submit`.

**Comment by Alchez** [comment]
@agritheory

> We just want to make that before_submit logic happens after the db rollback setpoint if there's an error in submit.

That makes sense. Let me check if that's already happening or if a change is required.

**Comment by Alchez** [comment]
@agritheory It seems like the rollback is happening correctly if a failure happens in `before_submit` or `on_submit`. Is there a case you've seen where this behaviour isn't happening?

**Pull request closed without merging**
